import "./globals.css";
import Header from "./components/Header";
import AOSContainer from '@/containers/AOSContainer';
import Footer from './components/Footer';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AOSContainer>
          <Header />
          {children}
          <Footer />
        </AOSContainer>
      </body>
    </html>
  );
}
